# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
warnings_are_errors: false

before_deploy: Rscript -e 'remotes::install_cran("pkgdown")'
deploy:
  github_token: $GITHUB_TOKEN
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true
